# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filesGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.filesGroupBox.setObjectName("filesGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filesGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonsWidget = QtWidgets.QWidget(self.filesGroupBox)
        self.buttonsWidget.setObjectName("buttonsWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonsWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addPushButton = QtWidgets.QPushButton(self.buttonsWidget)
        self.addPushButton.setObjectName("addPushButton")
        self.horizontalLayout_3.addWidget(self.addPushButton)
        self.editPushButton = QtWidgets.QPushButton(self.buttonsWidget)
        self.editPushButton.setEnabled(False)
        self.editPushButton.setObjectName("editPushButton")
        self.horizontalLayout_3.addWidget(self.editPushButton)
        self.removePushButton = QtWidgets.QPushButton(self.buttonsWidget)
        self.removePushButton.setEnabled(False)
        self.removePushButton.setObjectName("removePushButton")
        self.horizontalLayout_3.addWidget(self.removePushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sendPushButton = QtWidgets.QPushButton(self.buttonsWidget)
        self.sendPushButton.setEnabled(False)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout_3.addWidget(self.sendPushButton)
        self.verticalLayout.addWidget(self.buttonsWidget)
        self.filesTableWidget = QtWidgets.QTableWidget(self.filesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesTableWidget.sizePolicy().hasHeightForWidth())
        self.filesTableWidget.setSizePolicy(sizePolicy)
        self.filesTableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.filesTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.filesTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filesTableWidget.setProperty("showDropIndicator", False)
        self.filesTableWidget.setDragDropOverwriteMode(False)
        self.filesTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.filesTableWidget.setObjectName("filesTableWidget")
        self.filesTableWidget.setColumnCount(5)
        self.filesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(4, item)
        self.filesTableWidget.horizontalHeader().setVisible(True)
        self.filesTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.filesTableWidget)
        self.verticalLayout_2.addWidget(self.filesGroupBox)
        self.emailGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.emailGroupBox.setEnabled(False)
        self.emailGroupBox.setObjectName("emailGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.emailGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.toLabel = QtWidgets.QLabel(self.emailGroupBox)
        self.toLabel.setObjectName("toLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.toLabel)
        self.toLineEdit = QtWidgets.QLineEdit(self.emailGroupBox)
        self.toLineEdit.setReadOnly(True)
        self.toLineEdit.setObjectName("toLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.toLineEdit)
        self.subjectLabel = QtWidgets.QLabel(self.emailGroupBox)
        self.subjectLabel.setObjectName("subjectLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(self.emailGroupBox)
        self.subjectLineEdit.setReadOnly(True)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.bodyLabel = QtWidgets.QLabel(self.emailGroupBox)
        self.bodyLabel.setObjectName("bodyLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bodyLabel)
        self.bodyPlainTextEdit = QtWidgets.QPlainTextEdit(self.emailGroupBox)
        self.bodyPlainTextEdit.setReadOnly(True)
        self.bodyPlainTextEdit.setObjectName("bodyPlainTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bodyPlainTextEdit)
        self.attachmentLabel = QtWidgets.QLabel(self.emailGroupBox)
        self.attachmentLabel.setObjectName("attachmentLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.attachmentLabel)
        self.attachmentLineEdit = QtWidgets.QLineEdit(self.emailGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.attachmentLineEdit.setFont(font)
        self.attachmentLineEdit.setReadOnly(True)
        self.attachmentLineEdit.setObjectName("attachmentLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.attachmentLineEdit)
        self.verticalLayout_2.addWidget(self.emailGroupBox)
        self.tabWidget.addTab(self.mainTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settingsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.serverGroupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.serverGroupBox.setObjectName("serverGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.serverGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serverAddressLabel = QtWidgets.QLabel(self.serverGroupBox)
        self.serverAddressLabel.setObjectName("serverAddressLabel")
        self.horizontalLayout.addWidget(self.serverAddressLabel)
        self.serverAddressLineEdit = QtWidgets.QLineEdit(self.serverGroupBox)
        self.serverAddressLineEdit.setObjectName("serverAddressLineEdit")
        self.horizontalLayout.addWidget(self.serverAddressLineEdit)
        self.serverPortLabe = QtWidgets.QLabel(self.serverGroupBox)
        self.serverPortLabe.setObjectName("serverPortLabe")
        self.horizontalLayout.addWidget(self.serverPortLabe)
        self.serverPortSpinBox = QtWidgets.QSpinBox(self.serverGroupBox)
        self.serverPortSpinBox.setMinimum(1)
        self.serverPortSpinBox.setMaximum(65535)
        self.serverPortSpinBox.setProperty("value", 465)
        self.serverPortSpinBox.setObjectName("serverPortSpinBox")
        self.horizontalLayout.addWidget(self.serverPortSpinBox)
        self.tlsCheckBox = QtWidgets.QCheckBox(self.serverGroupBox)
        self.tlsCheckBox.setChecked(True)
        self.tlsCheckBox.setObjectName("tlsCheckBox")
        self.horizontalLayout.addWidget(self.tlsCheckBox)
        self.verticalLayout_3.addWidget(self.serverGroupBox)
        self.loginGroupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.loginGroupBox.setObjectName("loginGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.loginGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.usernameLabel = QtWidgets.QLabel(self.loginGroupBox)
        self.usernameLabel.setObjectName("usernameLabel")
        self.horizontalLayout_2.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.loginGroupBox)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.horizontalLayout_2.addWidget(self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.loginGroupBox)
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_2.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.loginGroupBox)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout_2.addWidget(self.passwordLineEdit)
        self.showPasswordCheckBox = QtWidgets.QCheckBox(self.loginGroupBox)
        self.showPasswordCheckBox.setChecked(False)
        self.showPasswordCheckBox.setObjectName("showPasswordCheckBox")
        self.horizontalLayout_2.addWidget(self.showPasswordCheckBox)
        self.verticalLayout_3.addWidget(self.loginGroupBox)
        self.senderGroupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.senderGroupBox.setObjectName("senderGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.senderGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.senderNameLabel = QtWidgets.QLabel(self.senderGroupBox)
        self.senderNameLabel.setObjectName("senderNameLabel")
        self.horizontalLayout_4.addWidget(self.senderNameLabel)
        self.senderNameLineEdit = QtWidgets.QLineEdit(self.senderGroupBox)
        self.senderNameLineEdit.setObjectName("senderNameLineEdit")
        self.horizontalLayout_4.addWidget(self.senderNameLineEdit)
        self.senderEmailLabel = QtWidgets.QLabel(self.senderGroupBox)
        self.senderEmailLabel.setObjectName("senderEmailLabel")
        self.horizontalLayout_4.addWidget(self.senderEmailLabel)
        self.senderEmailLineEdit = QtWidgets.QLineEdit(self.senderGroupBox)
        self.senderEmailLineEdit.setObjectName("senderEmailLineEdit")
        self.horizontalLayout_4.addWidget(self.senderEmailLineEdit)
        self.verticalLayout_3.addWidget(self.senderGroupBox)
        self.tasksFileGroupBox = QtWidgets.QGroupBox(self.settingsTab)
        self.tasksFileGroupBox.setObjectName("tasksFileGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tasksFileGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tasksFileLabel = QtWidgets.QLabel(self.tasksFileGroupBox)
        self.tasksFileLabel.setObjectName("tasksFileLabel")
        self.horizontalLayout_5.addWidget(self.tasksFileLabel)
        self.tasksFileLineEdit = QtWidgets.QLineEdit(self.tasksFileGroupBox)
        self.tasksFileLineEdit.setObjectName("tasksFileLineEdit")
        self.horizontalLayout_5.addWidget(self.tasksFileLineEdit)
        self.tasksFilePushButton = QtWidgets.QPushButton(self.tasksFileGroupBox)
        self.tasksFilePushButton.setObjectName("tasksFilePushButton")
        self.horizontalLayout_5.addWidget(self.tasksFilePushButton)
        self.verticalLayout_3.addWidget(self.tasksFileGroupBox)
        self.widget = QtWidgets.QWidget(self.settingsTab)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.settingsButtonBox = QtWidgets.QDialogButtonBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButtonBox.sizePolicy().hasHeightForWidth())
        self.settingsButtonBox.setSizePolicy(sizePolicy)
        self.settingsButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.settingsButtonBox.setObjectName("settingsButtonBox")
        self.horizontalLayout_6.addWidget(self.settingsButtonBox)
        self.verticalLayout_3.addWidget(self.widget)
        self.tabWidget.addTab(self.settingsTab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toLabel.setBuddy(self.toLineEdit)
        self.subjectLabel.setBuddy(self.subjectLineEdit)
        self.bodyLabel.setBuddy(self.bodyPlainTextEdit)
        self.attachmentLabel.setBuddy(self.attachmentLineEdit)
        self.serverAddressLabel.setBuddy(self.serverAddressLineEdit)
        self.serverPortLabe.setBuddy(self.serverPortSpinBox)
        self.usernameLabel.setBuddy(self.usernameLineEdit)
        self.passwordLabel.setBuddy(self.passwordLineEdit)
        self.senderNameLabel.setBuddy(self.senderNameLineEdit)
        self.senderEmailLabel.setBuddy(self.senderEmailLineEdit)
        self.tasksFileLabel.setBuddy(self.tasksFileLineEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.addPushButton)
        MainWindow.setTabOrder(self.addPushButton, self.editPushButton)
        MainWindow.setTabOrder(self.editPushButton, self.removePushButton)
        MainWindow.setTabOrder(self.removePushButton, self.sendPushButton)
        MainWindow.setTabOrder(self.sendPushButton, self.filesTableWidget)
        MainWindow.setTabOrder(self.filesTableWidget, self.toLineEdit)
        MainWindow.setTabOrder(self.toLineEdit, self.subjectLineEdit)
        MainWindow.setTabOrder(self.subjectLineEdit, self.bodyPlainTextEdit)
        MainWindow.setTabOrder(self.bodyPlainTextEdit, self.attachmentLineEdit)
        MainWindow.setTabOrder(self.attachmentLineEdit, self.serverAddressLineEdit)
        MainWindow.setTabOrder(self.serverAddressLineEdit, self.serverPortSpinBox)
        MainWindow.setTabOrder(self.serverPortSpinBox, self.tlsCheckBox)
        MainWindow.setTabOrder(self.tlsCheckBox, self.usernameLineEdit)
        MainWindow.setTabOrder(self.usernameLineEdit, self.passwordLineEdit)
        MainWindow.setTabOrder(self.passwordLineEdit, self.showPasswordCheckBox)
        MainWindow.setTabOrder(self.showPasswordCheckBox, self.senderNameLineEdit)
        MainWindow.setTabOrder(self.senderNameLineEdit, self.senderEmailLineEdit)
        MainWindow.setTabOrder(self.senderEmailLineEdit, self.tasksFileLineEdit)
        MainWindow.setTabOrder(self.tasksFileLineEdit, self.tasksFilePushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Periodical Email Sender"))
        self.filesGroupBox.setTitle(_translate("MainWindow", "Sending tasks"))
        self.addPushButton.setText(_translate("MainWindow", "Add"))
        self.editPushButton.setText(_translate("MainWindow", "Edit"))
        self.removePushButton.setText(_translate("MainWindow", "Remove"))
        self.sendPushButton.setText(_translate("MainWindow", "Send now"))
        item = self.filesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject"))
        item = self.filesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "To"))
        item = self.filesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Schedule"))
        item = self.filesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last run"))
        item = self.filesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Next run"))
        self.emailGroupBox.setTitle(_translate("MainWindow", "Email details"))
        self.toLabel.setText(_translate("MainWindow", "To"))
        self.subjectLabel.setText(_translate("MainWindow", "Subject"))
        self.bodyLabel.setText(_translate("MainWindow", "Content"))
        self.attachmentLabel.setText(_translate("MainWindow", "Attachment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Sending options"))
        self.serverGroupBox.setTitle(_translate("MainWindow", "Mail server settings"))
        self.serverAddressLabel.setText(_translate("MainWindow", "SMTP Server"))
        self.serverAddressLineEdit.setText(_translate("MainWindow", "smtp.gmail.com"))
        self.serverPortLabe.setText(_translate("MainWindow", "Port"))
        self.tlsCheckBox.setText(_translate("MainWindow", "SSL/TLS"))
        self.loginGroupBox.setTitle(_translate("MainWindow", "Login"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.usernameLineEdit.setPlaceholderText(_translate("MainWindow", "of your account"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "of your account"))
        self.showPasswordCheckBox.setText(_translate("MainWindow", "Show"))
        self.senderGroupBox.setTitle(_translate("MainWindow", "Sender information"))
        self.senderNameLabel.setText(_translate("MainWindow", "Name"))
        self.senderNameLineEdit.setPlaceholderText(_translate("MainWindow", "shown on the message"))
        self.senderEmailLabel.setText(_translate("MainWindow", "Email"))
        self.senderEmailLineEdit.setPlaceholderText(_translate("MainWindow", "shown on the message"))
        self.tasksFileGroupBox.setTitle(_translate("MainWindow", "Tasks file"))
        self.tasksFileLabel.setText(_translate("MainWindow", "Save to/load from"))
        self.tasksFileLineEdit.setPlaceholderText(_translate("MainWindow", "File path"))
        self.tasksFilePushButton.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))

